# Лабораторная работа №1 (NumPy)
## Выполнил Неженский Михаил Сергеевич, 6133-010402D

### 1. Взять из документации по numpy 12 любых функций / методов / операторов и продемонстрировать из работу в блокноте. Демонстрация каждой функции в своей ячейке. Если снабдите комментарием что делает данная операция — будет вообще прекрасно.

In [112]:
# Импортирвоание библиотек
import numpy as np
import pandas as pd
import sklearn.datasets

In [113]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])# Создание массива
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
a = np.zeros((3,3))# Создание массива размерности 3 на 3, который заполняется нулями
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [115]:
a = np.ones((3,3))# Создание массива размерности 3 на 3, который заполняется единицами
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [116]:
a = np.empty((3,3))# Создание массива размерности 3 на 3, который заполняется случайно(в зависимости от состояния памяти)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [117]:
a = np.arange(1,8,2)# Создание массива, элементы которого лежат в диапазоне значений от 1 до 8 с разницей равной 2
print(a)

[1 3 5 7]


In [118]:
a = np.linspace(1,8,3)# Создание массива, элементы которого лежат в диапазоне значений между 1 до 8, а 3 — это размер массива. Тип по умолчанию — float64.
print(a)

[1.  4.5 8. ]


In [119]:
a = np.logspace(1,8,3)# Тоже, что и предыдущее, но в логарифмической шкале
print(a)

[1.00000000e+01 3.16227766e+04 1.00000000e+08]


In [120]:
a = np.logspace(1,8,3)
print(np.sin(a))# Вывод синуса

[-0.54402111 -0.47507508  0.93163903]


In [121]:
a = np.arange(12).reshape(2,6)# Изменение количества измерений массива. От количества аргументов в reshape зависит, сколько измерений будет в массиве.
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [122]:
a = np.random.random((4,4))# Возвращает массив с заданным количеством измерений, где каждый элемент генерируется случайным образом.
print(a)

[[0.08413878 0.81777697 0.18915239 0.14688195]
 [0.01559847 0.86338095 0.92857998 0.79728999]
 [0.21023974 0.90282644 0.52946183 0.76239378]
 [0.89235828 0.24023931 0.84003197 0.69338606]]


In [123]:
a = np.exp([3])# Функция вернет ndarray с экспоненциальной величиной каждого элемента.
print(a)

[20.08553692]


In [124]:
a = np.sqrt([16])# Нахождение корня
print(a)

[4.]


### 2. Сгенерировать OLAP-куб, где фиксируем продажи товаров в розничной сети по магазинам. Оси: 0: ID группы товаров 1: ID магазина 2: день месяца, в котором осуществляются продажи (предположим у нас в OLAP-кубе собраны продажи за месяц). Содержимое ячейки: продажи в тыс. рублей данной категории товаров в данном магазине в данный день.

Рекомендуется сгенерировать статистически-правдопододные данные в ячейках. К примеру, будет странно, если продажи одной и той же группы товаров в соседние дни будут представлять из себя "белый шум". Пусть будет какой-то правдоподобное распределение на ваш вкус. Также продажи одних и тех же групп товаров в разных магазинах не могут отличаться в сотни и тысячи раз, максимум в разы. Подумайте как это обыграть используя различные функции генерации случайных чисел + "смекалку". "Правильного" решения тут нет, любое решение подойдёт, если будет понятно, что вы хотя бы попытались применить интеллект )


In [125]:
shop = 4
product = 3

In [126]:
shop = 1 + np.random.random(shop)  # Коэфициенты товарооборота магазина
shop

array([1.88514884, 1.34284954, 1.80357542, 1.69462759])

In [127]:
product = 1 + np.random.random(product) # Коэфициенты популярности товара
product

array([1.96844232, 1.5081158 , 1.31658963])

In [128]:
olap = np.ones((len(product),len(shop),10), dtype=int)
olap

array([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]])

In [129]:
for i in range(len(product)):
    for j in range(len(shop)):
        for k in range(10):
            olap[i,j,k] = np.random.normal(1000*product[i]*shop[j], 33, 8)[0] # При генерации используем нормальное распределение
print(olap)

[[[3616 3670 3719 3694 3749 3700 3743 3651 3698 3754]
  [2657 2616 2605 2585 2622 2625 2614 2715 2638 2610]
  [3576 3496 3542 3577 3574 3539 3574 3510 3558 3508]
  [3357 3306 3347 3342 3311 3322 3308 3357 3328 3351]]

 [[2838 2860 2827 2818 2806 2872 2864 2857 2816 2809]
  [2043 2061 1963 2019 2084 2041 1995 2019 2009 2058]
  [2735 2731 2790 2735 2713 2731 2676 2769 2719 2680]
  [2527 2573 2473 2562 2569 2535 2582 2539 2544 2611]]

 [[2450 2441 2500 2516 2431 2529 2483 2547 2466 2455]
  [1758 1728 1829 1747 1795 1791 1816 1767 1723 1730]
  [2371 2381 2439 2294 2382 2372 2431 2293 2396 2417]
  [2191 2282 2231 2233 2214 2239 2240 2249 2216 2232]]]


### 3. Для получившегося OLAP-куба посчитать суммарные, средние, минимальные и максимальные продажи (на самом деле любые агрегатные функции можно использовать), зафиксировав значения по одной, двум или трём осям: например взять какой-то определённый набор товаров и набор городов или диапазон дней и сагрегировать данные по всем ячейкам из зафиксированного набора. Пример: получить сумму, среднее, минимум и максимум по продажам 10-20 чисел месяца для товаров [1,3,4] по всем городам (или по конкретному набору городов). Попробуйте различные варианты индексации и различные варианты срезов, насколько хватит фантазии.

In [130]:
np.sum(olap, axis=0) # Получим суммы проданных товаров 1 вида во все дни и во всех магазинах

array([[8904, 8971, 9046, 9028, 8986, 9101, 9090, 9055, 8980, 9018],
       [6458, 6405, 6397, 6351, 6501, 6457, 6425, 6501, 6370, 6398],
       [8682, 8608, 8771, 8606, 8669, 8642, 8681, 8572, 8673, 8605],
       [8075, 8161, 8051, 8137, 8094, 8096, 8130, 8145, 8088, 8194]])

In [131]:
np.min(olap, axis=1) # Получим минимальное значение проданных товаров всех видов во все дни в 1 магазине

array([[2657, 2616, 2605, 2585, 2622, 2625, 2614, 2715, 2638, 2610],
       [2043, 2061, 1963, 2019, 2084, 2041, 1995, 2019, 2009, 2058],
       [1758, 1728, 1829, 1747, 1795, 1791, 1816, 1767, 1723, 1730]])

In [132]:
np.max(olap[1:3], axis=2) # Получим максимальное значение проданных товаров 2 и 3 вида во всех магазинах в 1 день

array([[2872, 2084, 2790, 2611],
       [2547, 1829, 2439, 2282]])

In [133]:
np.mean(olap[1:2,:,1:3]) # Получим среднее значение проданных товаров 2 вида во 2 и 3 день во всех магазинах

2534.75